// <auto-generated />
using EstacionaBem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstacionaBem.Migrations
{
    [DbContext(typeof(ParkContext))]
    [Migration("20230714231237_ThirdMigration")]
    partial class ThirdMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("EstacionaBem.Models.PriceEntryModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("precoHoraAdicional")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("precoHoraInicial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vigenciaFim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vigenciaInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("EstacionaBem.Models.VehicleEntryModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("chegada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("preco")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("saida")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Parkings");
                });
#pragma warning restore 612, 618
        }
    }
}
