// <auto-generated />
using System;
using EstacionaBem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EstacionaBem.Migrations
{
    [DbContext(typeof(ParkContext))]
    [Migration("20230717152907_EleventhMigration")]
    partial class EleventhMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("EstacionaBem.Models.EstadiaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("chegada")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("preco")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("saida")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("estadias");
                });

            modelBuilder.Entity("EstacionaBem.Models.PrecoModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float?>("precoHoraAdicional")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<float?>("precoHoraInicial")
                        .IsRequired()
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("vigenciaFim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("vigenciaInicio")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("precos");
                });
#pragma warning restore 612, 618
        }
    }
}
